[package]
name = "notable"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
directories = "5.0.1"
open = "3.0"
tokio = { version = "1.39.2", features = ["rt", "macros"] }
warp = "0.3.7"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
